name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # 10分ごとに実行

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to keep Render alive
        run: curl -s https://animepilgrimage.onrender.com/hello

